name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        laravel: [8, 9, 10, 11]
        exclude:
          - php: 7.4
            laravel: 9
          - php: 7.4
            laravel: 10
          - php: 7.4
            laravel: 11

          - php: 8.0
            laravel: 8  
          - php: 8.0
            laravel: 10
          - php: 8.0
            laravel: 11

          - php: 8.1
            laravel: 8  
          - php: 8.1
            laravel: 9
          - php: 8.1
            laravel: 11
            
          - php: 8.2
            laravel: 8
          - php: 8.2
            laravel: 9
          - php: 8.2
            laravel: 10
            
          - php: 8.3
            laravel: 7
          - php: 8.3
            laravel: 8
          - php: 8.3
            laravel: 9
          - php: 8.3
            laravel: 10

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --prefer-dist --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: composer test
        
  php-cs-fixer:
      runs-on: ubuntu-latest
  
      strategy:
        fail-fast: true
        matrix:
          php: [8.3]
          laravel: [^11.0]
  
      name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
  
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip
            coverage: none
  
        - name: Install dependencies
          run: composer update --prefer-dist --no-interaction --no-progress
  
        - name: Run PHP CS Fixer
          run: composer format
  
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Fix styling
